// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

//! Post-execution system-invariant checks for transaction execution.
//!
//! All of the defense-in-depth checks that verify the finalized execution results satisfy system
//! invariants live here, behind the [`InvariantChecker`] API: that the transaction neither mints
//! nor burns SUI, that balance-accumulator withdrawals stay authorized, and that every modified
//! object traces back to an authenticated owner. [`TemporaryStore`] owns one `InvariantChecker`,
//! forwards execution observations needed by invariant checks to it, and defers to it for
//! the checks. Keeping it in its own module keeps the invariant accounting -- which reaches across
//! gas, accumulator events, settlement SUI, per-object storage rebates, and object ownership -- out
//! of the main store code.
//!
//! Note these are invariant *assertions* (a failure means a bug, and aborts or panics), distinct
//! from transaction-validation guards like `TemporaryStore::check_accumulator_amounts_representable`
//! that can legitimately reject a well-formed transaction.
//!
//! [`TemporaryStore`]: crate::temporary_store::TemporaryStore

use std::ops::Range;

use containers::{BTreeMap, BTreeSet, Bump, Vec};
use messages::base::ObjectId;

/// Holds invariant-check-only bookkeeping accumulated during execution and exposes the
/// post-execution system-invariant checks (SUI conservation, balance-accumulator authorization,
/// object ownership) as its API.
///
/// Immutable check inputs and execution results are read from the owning [`TemporaryStore`]
/// passed to each check method.
///
/// [`TemporaryStore`]: crate::temporary_store::TemporaryStore
pub(crate) struct InvariantChecker<'a> {
    /// A map from wrapped object to its container, used to authenticate wrapped mutations.
    wrapped_object_containers: BTreeMap<'a, ObjectId, ObjectId>,
    /// All object IDs generated by the object runtime, including created-and-then-deleted objects.
    generated_runtime_ids: BTreeSet<'a, ObjectId>,
    /// Index ranges into `execution_results.accumulator_events` for events emitted from PTB
    /// (Move) execution. Each `record_ptb_event_range` call appends a contiguous range
    /// bracketing the merge. Any index outside these ranges was emitted by the runtime outside
    /// of PTB execution (currently only `gas_charger`'s `add_accumulator_event`). Consumed by
    /// `check_address_balance_changes` to gate non-PTB-emitted events behind input reservations.
    /// Cleared on `drop_writes` since the underlying events are also cleared. A `Vec` is
    /// sufficient because real transactions run the PTB at most a handful of times.
    ptb_emitted_accumulator_event_ranges: Vec<'a, Range<usize>>,
}

impl<'a> InvariantChecker<'a> {
    /// The reference's `Default`, in `bump`.
    pub(crate) fn new_in(bump: &'a Bump) -> Self {
        Self {
            wrapped_object_containers: BTreeMap::new_in(bump),
            generated_runtime_ids: BTreeSet::new_in(bump),
            ptb_emitted_accumulator_event_ranges: Vec::new_in(bump),
        }
    }

    pub(crate) fn save_wrapped_object_containers(
        &mut self,
        wrapped_object_containers: BTreeMap<'a, ObjectId, ObjectId>,
    ) {
        #[cfg(debug_assertions)]
        {
            for (id, container1) in &wrapped_object_containers {
                if let Some(container2) = self.wrapped_object_containers.get(id) {
                    assert_eq!(container1, container2);
                }
            }
            for (id, container1) in &self.wrapped_object_containers {
                if let Some(container2) = wrapped_object_containers.get(id) {
                    assert_eq!(container1, container2);
                }
            }
        }
        // Merge the two maps because we may be calling the execution engine more than once
        // (e.g. in advance epoch transaction, where we may be publishing a new system package).
        self.wrapped_object_containers
            .extend(wrapped_object_containers);
    }

    pub(crate) fn save_generated_object_ids(&mut self, generated_ids: BTreeSet<'a, ObjectId>) {
        #[cfg(debug_assertions)]
        {
            for id in &self.generated_runtime_ids {
                assert!(!generated_ids.contains(id))
            }
            for id in &generated_ids {
                assert!(!self.generated_runtime_ids.contains(id));
            }
        }
        self.generated_runtime_ids.extend(generated_ids);
    }

    /// Record that the accumulator events in `[start, end)` (indices into
    /// `execution_results.accumulator_events`) were emitted by PTB (Move) execution. `start`/`end`
    /// are the lengths of the accumulator-event vec before/after a `merge_results`. The
    /// address-balance change invariant uses this set to distinguish trusted PTB-emitted events
    /// from runtime-emitted ones.
    pub(crate) fn record_ptb_event_range(&mut self, start: usize, end: usize) {
        debug_assert!(
            start <= end,
            "merge_results should not shrink accumulator_events"
        );
        let (start, end) = (start.min(end), start.max(end));
        let range = start..end;
        match self.ptb_emitted_accumulator_event_ranges.last_mut() {
            // Coalesce with the previous PTB range if no runtime events were added in between.
            Some(last) if last.end == range.start => last.end = range.end,
            _ => self.ptb_emitted_accumulator_event_ranges.push(range),
        }
    }
}
