[package]
name = "validation"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
base64ct.workspace = true
fastcrypto.workspace = true
roaring.workspace = true
blake2.workspace = true
containers.workspace = true
messages.workspace = true
protocol-config.workspace = true

[dev-dependencies]
containers.workspace = true

[lints]
workspace = true
