[package]
name = "validation"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
base64ct.workspace = true
bcs.workspace = true
fastcrypto.workspace = true
fastcrypto-zkp.workspace = true
imbl.workspace = true
roaring.workspace = true
serde.workspace = true
serde_json.workspace = true
blake2.workspace = true
containers.workspace = true
messages.workspace = true
protocol-config.workspace = true

[dev-dependencies]
flate2 = "1"
serde_json.workspace = true
containers.workspace = true

[lints]
workspace = true
